image: jakzal/phpqa:php8.1

before_script:
    - composer install

cache:
    paths:
        - vendor/


phpunit:
    image: php:8.1-apache
    stage: Tests
    services:
        - name: mysql:8.0
          alias: mysql
    variables:
        MYSQL_ROOT_PASSWORD: pass_test
        MYSQL_DATABASE: myapptest
        MYSQL_USER: myapptest
        MYSQL_PASSWORD: myapptest
        DATABASE_URL: 'mysql://myapptest:myapptest@mysql:3306/myapptest'
    before_script:
        - apt-get update && apt-get install -y git libzip-dev nodejs npm
        - curl -sSK https://getcomposer.org/installer -o composer-script.sh | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
        - docker-php-ext-install mysqli pdo pdo_mysql zip
        - php bin/console doctrine:database:drop --force --env=test
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:migration:migrate --env=test
        - php bin/console doctrine:fixtures:load --no-interaction
        - echo $PATH
        - ls -l /usr/local/bin/composer
        - cat /usr/local/bin/composer-script.sh
        - /usr/local/bin/composer install
        - npm install
        - npm run build
    script:
        - php bin/phpunit
    allow_failure: false