image: php:8.1-apache

stages:
  - Tests

services:
  - name: mysql:8.0
    alias: mysql

variables:
  MYSQL_ROOT_PASSWORD: pass_test
  MYSQL_DATABASE: myapptest
  MYSQL_USER: myapptest
  MYSQL_PASSWORD: myapptest
  DATABASE_URL: 'mysql://myapptest:myapptest@mysql:3306/myapptest'

before_script:
  - apt-get update && apt-get install -y git libzip-dev nodejs npm
  - curl -sSK https://getcomposer.org/installer -o composer-script.sh && php composer-script.sh -- --disable-tls && mv composer.phar /usr/local/bin/composer
  - docker-php-ext-install mysqli pdo pdo_mysql zip
  - composer install

cache:
  paths:
    - vendor/

phpunit:
  stage: Tests
  script:
    - php bin/phpunit
  allow_failure: false
